---
- name: Setup Kong Gateway 
  include_tasks: setup.yml
  when: not reset | default(false)

- name: Reset Kong Gateway 
  include_tasks: reset.yml
  when: reset | default(false)

- name: Configure Kong to use PostgreSQL
  template:
    src: kong.conf.j2
    dest: /etc/kong/kong.conf
  notify:
    - Restart Kong
