---
- name: Apply sudo safeguards
  import_tasks: sudo_safeguard.yml
  tags: [sudo, security]
  when: not reset | bool

- name: Prepare hypervisor hosts
  import_tasks: setup.yml
  when: not reset | bool

- name: Reset host preparation
  import_tasks: reset.yml
  when: reset | bool
