---
reset: False

external_dns_log_level: "debug"
external_dns_namespace: external-dns-unifi
external_dns_chart_version: v0.3.4
external_dns_txt_owner_id: external-dns-unifi
external_dns_txt_prefix: microk8s-home-lab.
external_dns_sources:
  - ingress
  - service

external_dns_domain_filters:
  - infiquetra.com

unifi_host: https://10.220.1.1
unifi_external_controller: "false"
unifi_secret_key: external-dns-unifi-secret
unifi_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65636634303638613239666635613331343032353465613832663138333231383132376264393239
          3430313565373539326366306462326630373933616234310a393761633739383865393238383530
          32633134356263633530373937383564313963616164393637333833633439376536653664313831
          3464613739306537350a376564346466623839653366346563323033616233356661333165326332
          6262

unifi_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64613966316465323432316463633437373061323730356437353932356430323731313038373738
          3261303563653461303935333537386233613764333035610a666364633861623833393365396564
          33363039383436326431633337343436386434366439303661373035303833373434363463663831
          3361363564666138340a356261386138666366366362646531303839323631333838313439356533
          3065
