---
# libvirt role defaults
reset: False

# Libvirt packages
libvirt_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - virtinst
  - libvirt-daemon
  - libguestfs-tools
  - python3-libvirt

# User to add to libvirt groups
libvirt_user: "{{ ansible_user }}"

# Default network configuration
libvirt_default_network: default
libvirt_network_autostart: yes
