---
reset: False
# hostgroup whose members will form high-availability microk8s cluster
microk8s_cluster: "cluster"

# admin username for kubernetes cluster
kube_admin_user: jefcox

ansible_become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36343734633863323932616138323561363733353662383230366337343339386461626162396261
          3335373235656565643361333833376664303338333763630a306230323533336665663863376331
          66313164653238333133396538633561336263383664343934613638636465363537636131393661
          6262346666666333340a303266376331386532656132663037373130656138656132313566656431
          3766

docker_hub_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34653436326233613964376532663035383632663537613261626562623539356435643638366530
          3764653636376436336465373638373061616132343863660a636138346665333664333634363536
          35343430373338353961613765313734626364613932383364616231653433363963333666623934
          3431653035303262660a613865663935353736323963396435303833646534323063306633636366
          31323633356465313563643638333131303930666266333530393462306161313530386465326564
          6263633039333933613331343132396136356132333165316363
vault_discord_bot_token_zeus: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30623133646536653965326462363835636539326434333961613865633632623261363732636336
          6634646635643134386132383234373339396435386464330a666439613464393866666432626631
          36373332663735323163383262326333393537306137333664343962336539393134386437343030
          3633313663356361630a653538313661376236396636373165303661326433386437643563353535
          66643433666131633961353738356433646166326332656466636639386538313934373763316330
          31313231326534356530616635613739653639353539326561356336306366336334633332633030
          63346533616566326632613662666630636431383061303636346338333132386363363266363438
          66303139343261663736

vault_discord_bot_token_athena: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38653332373633303835343838316233666234316162386666636265613166376161393564326531
          3936363131333832306464313038373663626532373962300a353762323265313537316566346261
          32393931343165323461393738656439363862346637373366363133336665623737383839373530
          6433653234356537620a356264306364386466356365613663363265303631623461653466303433
          34393331306561326164383564376264383433383039663632323263653532306635396532663633
          39393736313339333030393736376664333962643362323839396261343634646365666231346538
          62366437393062383665326165373139656230326333333162336135303361646565343966323762
          31323436393530306338

vault_discord_bot_token_apollo: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38366334353436323766396431346333373939356362626133636166613239316233353033373936
          6162633033346632363863313737326130373232373336360a346233343136613664616339623835
          63396663396561376137373463306664613866343339316334343832636533613563353963646662
          3338316332366133630a626265313637373831346265646361653561386135643434643563343764
          35373263306466323734663063646438306563626337326665653637313965316137613261303764
          32356632646139366534316665386261323335366633663334653765643365616435316333613438
          36326133636230363062643235643466386665623634333962313431333939663236363966643235
          31613336633139653130

vault_discord_bot_token_artemis: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38346139323366386464356663666535323331316236613861623337383335663238623264336132
          6533333264323638343731356234396636316330336630390a313334376337373636353866303138
          61343837343266656135393237383336616634353738616562303531306366373930306536363464
          6430663032616231360a346265366431366538346431636237376566303937366633623966363438
          32653164623036303065343439373563333361383237306363333038636362356136656231636232
          65643630333534663639356634353531316365626431373939363861353837333630613435643766
          35353736306230616439376538306562663037373235353137346539313861306638306162633630
          31366437623634646435

vault_discord_bot_token_hermes: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38323133373234643961303031616465316635326132383833323166363961613539656530383366
          3336663331303038663435313935393837353264313235300a326535313566393035303561316632
          63633333336361393561623137333263663837623936663865623862313464343537353862396230
          3465303638653530360a333032356336336532666463313234353565313465636339666162633463
          39643461613266356661326332326662633361343738373462383163306664373764623533336431
          31373334616462633365383765366265383963646231336363376632383836313863663439303239
          61623032633963373032626439643865306439373039373734613536636463343334376265356631
          33633435353365393638

vault_discord_bot_token_perseus: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66643735363139386563363636663865306665383534396639616132653639646164373936353635
          3538313035636138333761393932393865303261336361310a326333623962663964346430306431
          34343062386362633731376234333731343962613566643363663935383439336430373163323438
          6633323261383435630a643037663732376265353438653635366264323263323362653663323861
          31643166643365363966373337613962333964336537336136623064366164363432623537356338
          39333665666133376336366164333933376332303130353330626462613365336161393766663764
          31393766373366303762356266353930643961646163373139336539366363383361393532306462
          63623636363438383138

vault_discord_bot_token_prometheus: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30666663393334663063393938373133396335313938356331666536346437376439373738623930
          3532326237616563363030646238616233363739383439360a313037653739643366326132653737
          66396163393933653361656238393531613165306565363032363666313436643362383364643135
          3364306532323862660a373931666432383134643539626132303138353239313433386163343135
          38313136353832643037663235656632356330356664306331346433623834343962393265343064
          34343338663039303163363231646161623232613131386435616238303734616436376639303039
          61333836336531613864303533633839656238366162613363313562343961396665303130313362
          35626236363663383235

vault_discord_bot_token_ares: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37303966366637313239356635656461323832633634383535646433353765623963326135623964
          3363653965623964373637356537393361333965363464310a663231646532336564636338353466
          66386561626339613139613835646161313262333333623838616264646361656661373263623434
          6631633632656265620a356632663837636262643965383330373730356436393262323865353832
          34396561613937643562633338343764323266346531326530666363613864346634333563623035
          38626166373635306131346130643832363339623266313437336332303533383064656338386161
          38313236356632636562373463393434643562623337633231656463313666346564613933643035
          38336264616231376136

vault_discord_bot_token_freya: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64353163373435663537336365313933383632663066306263383566366661383963306162623166
          6232373231393463396131653164343561663165386135620a646135653539316162376265616162
          36333038613035653832386363656634633165383061653466663438353232343831653965303832
          3334313365623661630a663035626164663234346439393732663162373937613964666233633433
          64643336316235633033303066626466643438343332396263636131636561336534353766396537
          36653733656632396530633939333435646263633232633864623166373636383930386462326539
          38373735343964613932336439336161616339346366613933326165336662363637643265356537
          37336166613437633365

